# Generated by Django 4.1.3 on 2022-11-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='task',
            name='planned_ords',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='real_ords',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Todo'), (1, 'In Progress'), (2, 'Ready To Verify'), (3, 'Done')], default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='storypoints',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
