# Generated by Django 4.1.3 on 2022-11-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_description_task_planned_ords_task_real_ords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='planned_ords',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='real_ords',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='storypoints',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
