# Generated by Django 4.1.3 on 2022-11-02 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ready_to_take', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('ready_to_verify', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('planned_ords', models.FloatField()),
                ('storypoints', models.FloatField()),
                ('real_ords', models.FloatField()),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.taskstatus')),
            ],
        ),
    ]
